# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculadoraInt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculadora(object):
    def setupUi(self, Calculadora):
        Calculadora.setObjectName("Calculadora")
        Calculadora.resize(289, 350)
        Calculadora.setMaximumSize(QtCore.QSize(289, 350))
        self.centralwidget = QtWidgets.QWidget(Calculadora)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FrameSuperior = QtWidgets.QFrame(self.frame)
        self.FrameSuperior.setMinimumSize(QtCore.QSize(0, 42))
        self.FrameSuperior.setStyleSheet("QFrame{\n"
"background-color:#0070C0;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:orange;\n"
"border-radius:20px;\n"
"}")
        self.FrameSuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameSuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameSuperior.setObjectName("FrameSuperior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.FrameSuperior)
        self.horizontalLayout.setContentsMargins(8, 3, 8, 8)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DESINGLASS = QtWidgets.QLabel(self.FrameSuperior)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DESINGLASS.setFont(font)
        self.DESINGLASS.setObjectName("DESINGLASS")
        self.horizontalLayout.addWidget(self.DESINGLASS)
        spacerItem = QtWidgets.QSpacerItem(646, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.BTMin = QtWidgets.QPushButton(self.FrameSuperior)
        self.BTMin.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/Minimizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTMin.setIcon(icon)
        self.BTMin.setIconSize(QtCore.QSize(28, 28))
        self.BTMin.setObjectName("BTMin")
        self.horizontalLayout.addWidget(self.BTMin)
        self.BTMax2 = QtWidgets.QPushButton(self.FrameSuperior)
        self.BTMax2.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMax2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/Maximizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTMax2.setIcon(icon1)
        self.BTMax2.setIconSize(QtCore.QSize(18, 18))
        self.BTMax2.setObjectName("BTMax2")
        self.horizontalLayout.addWidget(self.BTMax2)
        self.BTMax = QtWidgets.QPushButton(self.FrameSuperior)
        self.BTMax.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMax.setText("")
        self.BTMax.setIcon(icon1)
        self.BTMax.setIconSize(QtCore.QSize(18, 18))
        self.BTMax.setObjectName("BTMax")
        self.horizontalLayout.addWidget(self.BTMax)
        self.BTCerar = QtWidgets.QPushButton(self.FrameSuperior)
        self.BTCerar.setMinimumSize(QtCore.QSize(40, 40))
        self.BTCerar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/Cerrar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTCerar.setIcon(icon2)
        self.BTCerar.setIconSize(QtCore.QSize(28, 28))
        self.BTCerar.setObjectName("BTCerar")
        self.horizontalLayout.addWidget(self.BTCerar)
        self.verticalLayout_2.addWidget(self.FrameSuperior)
        self.FrameContenido = QtWidgets.QFrame(self.frame)
        self.FrameContenido.setStyleSheet("QFrame{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:White;\n"
"border:0px solid #14C8DC;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#A4D6DC;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#DCD8A4;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.FrameContenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameContenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameContenido.setObjectName("FrameContenido")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.FrameContenido)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Resultado = QtWidgets.QTextEdit(self.FrameContenido)
        self.Resultado.setMinimumSize(QtCore.QSize(0, 55))
        self.Resultado.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Resultado.setStyleSheet("QTextEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}")
        self.Resultado.setObjectName("Resultado")
        self.verticalLayout_3.addWidget(self.Resultado)
        self.Edicion = QtWidgets.QTextEdit(self.FrameContenido)
        self.Edicion.setMinimumSize(QtCore.QSize(0, 45))
        self.Edicion.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Edicion.setStyleSheet("QTextEdit{\n"
"background-color:Gray;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}")
        self.Edicion.setObjectName("Edicion")
        self.verticalLayout_3.addWidget(self.Edicion)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.BTPar1 = QtWidgets.QPushButton(self.FrameContenido)
        self.BTPar1.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTPar1.setFont(font)
        self.BTPar1.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTPar1.setAutoRepeatDelay(500)
        self.BTPar1.setAutoRepeatInterval(500)
        self.BTPar1.setAutoDefault(False)
        self.BTPar1.setObjectName("BTPar1")
        self.horizontalLayout_7.addWidget(self.BTPar1)
        self.BTPar2 = QtWidgets.QPushButton(self.FrameContenido)
        self.BTPar2.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTPar2.setFont(font)
        self.BTPar2.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTPar2.setAutoRepeatDelay(500)
        self.BTPar2.setAutoRepeatInterval(500)
        self.BTPar2.setObjectName("BTPar2")
        self.horizontalLayout_7.addWidget(self.BTPar2)
        self.BTC = QtWidgets.QPushButton(self.FrameContenido)
        self.BTC.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTC.setFont(font)
        self.BTC.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTC.setAutoRepeatDelay(500)
        self.BTC.setAutoRepeatInterval(500)
        self.BTC.setObjectName("BTC")
        self.horizontalLayout_7.addWidget(self.BTC)
        self.BTDelete = QtWidgets.QPushButton(self.FrameContenido)
        self.BTDelete.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTDelete.setFont(font)
        self.BTDelete.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTDelete.setAutoRepeatDelay(500)
        self.BTDelete.setAutoRepeatInterval(500)
        self.BTDelete.setObjectName("BTDelete")
        self.horizontalLayout_7.addWidget(self.BTDelete)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.BT7 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT7.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT7.setFont(font)
        self.BT7.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT7.setObjectName("BT7")
        self.horizontalLayout_6.addWidget(self.BT7)
        self.BT8 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT8.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT8.setFont(font)
        self.BT8.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT8.setObjectName("BT8")
        self.horizontalLayout_6.addWidget(self.BT8)
        self.BT9 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT9.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT9.setFont(font)
        self.BT9.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT9.setObjectName("BT9")
        self.horizontalLayout_6.addWidget(self.BT9)
        self.BTDiv = QtWidgets.QPushButton(self.FrameContenido)
        self.BTDiv.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTDiv.setFont(font)
        self.BTDiv.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTDiv.setObjectName("BTDiv")
        self.horizontalLayout_6.addWidget(self.BTDiv)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BT5 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT5.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT5.setFont(font)
        self.BT5.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT5.setObjectName("BT5")
        self.horizontalLayout_5.addWidget(self.BT5)
        self.BT6 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT6.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT6.setFont(font)
        self.BT6.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT6.setObjectName("BT6")
        self.horizontalLayout_5.addWidget(self.BT6)
        self.BT4 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT4.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT4.setFont(font)
        self.BT4.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT4.setObjectName("BT4")
        self.horizontalLayout_5.addWidget(self.BT4)
        self.BTMult = QtWidgets.QPushButton(self.FrameContenido)
        self.BTMult.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTMult.setFont(font)
        self.BTMult.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTMult.setObjectName("BTMult")
        self.horizontalLayout_5.addWidget(self.BTMult)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BT1 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT1.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT1.setFont(font)
        self.BT1.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT1.setObjectName("BT1")
        self.horizontalLayout_4.addWidget(self.BT1)
        self.BT2 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT2.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT2.setFont(font)
        self.BT2.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT2.setObjectName("BT2")
        self.horizontalLayout_4.addWidget(self.BT2)
        self.BT3 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT3.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BT3.setFont(font)
        self.BT3.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT3.setObjectName("BT3")
        self.horizontalLayout_4.addWidget(self.BT3)
        self.BTSum = QtWidgets.QPushButton(self.FrameContenido)
        self.BTSum.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTSum.setFont(font)
        self.BTSum.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTSum.setObjectName("BTSum")
        self.horizontalLayout_4.addWidget(self.BTSum)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BT0 = QtWidgets.QPushButton(self.FrameContenido)
        self.BT0.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(11)
        self.BT0.setFont(font)
        self.BT0.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BT0.setObjectName("BT0")
        self.horizontalLayout_3.addWidget(self.BT0)
        self.BTPunto = QtWidgets.QPushButton(self.FrameContenido)
        self.BTPunto.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTPunto.setFont(font)
        self.BTPunto.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTPunto.setObjectName("BTPunto")
        self.horizontalLayout_3.addWidget(self.BTPunto)
        self.BTRest = QtWidgets.QPushButton(self.FrameContenido)
        self.BTRest.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.BTRest.setFont(font)
        self.BTRest.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTRest.setObjectName("BTRest")
        self.horizontalLayout_3.addWidget(self.BTRest)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTIgual = QtWidgets.QPushButton(self.FrameContenido)
        self.BTIgual.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTIgual.setFont(font)
        self.BTIgual.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTIgual.setObjectName("BTIgual")
        self.horizontalLayout_2.addWidget(self.BTIgual)
        self.BTRaiz = QtWidgets.QPushButton(self.FrameContenido)
        self.BTRaiz.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTRaiz.setFont(font)
        self.BTRaiz.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid rgb(255,255,255);\n"
"}")
        self.BTRaiz.setObjectName("BTRaiz")
        self.horizontalLayout_2.addWidget(self.BTRaiz)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 5)
        self.verticalLayout_4.setStretch(2, 5)
        self.verticalLayout_4.setStretch(3, 5)
        self.verticalLayout_4.setStretch(4, 5)
        self.verticalLayout_4.setStretch(5, 5)
        self.verticalLayout_4.setStretch(6, 5)
        self.verticalLayout_4.setStretch(7, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addWidget(self.FrameContenido)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout.addWidget(self.frame)
        Calculadora.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculadora)
        QtCore.QMetaObject.connectSlotsByName(Calculadora)

    def retranslateUi(self, Calculadora):
        _translate = QtCore.QCoreApplication.translate
        Calculadora.setWindowTitle(_translate("Calculadora", "MainWindow"))
        self.DESINGLASS.setText(_translate("Calculadora", "Calculadora"))
        self.BTPar1.setText(_translate("Calculadora", "("))
        self.BTPar2.setText(_translate("Calculadora", ")"))
        self.BTC.setText(_translate("Calculadora", "C"))
        self.BTDelete.setText(_translate("Calculadora", "⌫"))
        self.BT7.setText(_translate("Calculadora", "7"))
        self.BT8.setText(_translate("Calculadora", "8"))
        self.BT9.setText(_translate("Calculadora", "9"))
        self.BTDiv.setText(_translate("Calculadora", "÷"))
        self.BT5.setText(_translate("Calculadora", "5"))
        self.BT6.setText(_translate("Calculadora", "6"))
        self.BT4.setText(_translate("Calculadora", "4"))
        self.BTMult.setText(_translate("Calculadora", "x"))
        self.BT1.setText(_translate("Calculadora", "1"))
        self.BT2.setText(_translate("Calculadora", "2"))
        self.BT3.setText(_translate("Calculadora", "3"))
        self.BTSum.setText(_translate("Calculadora", "+"))
        self.BT0.setText(_translate("Calculadora", "0"))
        self.BTPunto.setText(_translate("Calculadora", "."))
        self.BTRest.setText(_translate("Calculadora", "-"))
        self.BTIgual.setText(_translate("Calculadora", "="))
        self.BTRaiz.setText(_translate("Calculadora", "√"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculadora = QtWidgets.QMainWindow()
    ui = Ui_Calculadora()
    ui.setupUi(Calculadora)
    Calculadora.show()
    sys.exit(app.exec_())
