# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DivisasInt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Divisas(object):
    def setupUi(self, Divisas):
        Divisas.setObjectName("Divisas")
        Divisas.resize(620, 485)
        Divisas.setMinimumSize(QtCore.QSize(0, 0))
        Divisas.setMaximumSize(QtCore.QSize(620, 485))
        self.centralwidget = QtWidgets.QWidget(Divisas)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FrameSuperior = QtWidgets.QFrame(self.frame)
        self.FrameSuperior.setStyleSheet("QFrame{\n"
"background-color:#0070C0;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:orange;\n"
"border-radius:20px;\n"
"}")
        self.FrameSuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameSuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameSuperior.setObjectName("FrameSuperior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.FrameSuperior)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DESINGLASS = QtWidgets.QLabel(self.FrameSuperior)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DESINGLASS.setFont(font)
        self.DESINGLASS.setObjectName("DESINGLASS")
        self.horizontalLayout.addWidget(self.DESINGLASS)
        spacerItem = QtWidgets.QSpacerItem(261, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.BTMin = QtWidgets.QPushButton(self.FrameSuperior)
        self.BTMin.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/Minimizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTMin.setIcon(icon)
        self.BTMin.setIconSize(QtCore.QSize(28, 28))
        self.BTMin.setObjectName("BTMin")
        self.horizontalLayout.addWidget(self.BTMin)
        self.BTMax2 = QtWidgets.QPushButton(self.FrameSuperior)
        self.BTMax2.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMax2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/Maximizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTMax2.setIcon(icon1)
        self.BTMax2.setIconSize(QtCore.QSize(18, 18))
        self.BTMax2.setObjectName("BTMax2")
        self.horizontalLayout.addWidget(self.BTMax2)
        self.BTMax = QtWidgets.QPushButton(self.FrameSuperior)
        self.BTMax.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMax.setText("")
        self.BTMax.setIcon(icon1)
        self.BTMax.setIconSize(QtCore.QSize(18, 18))
        self.BTMax.setObjectName("BTMax")
        self.horizontalLayout.addWidget(self.BTMax)
        self.BTCerar = QtWidgets.QPushButton(self.FrameSuperior)
        self.BTCerar.setMinimumSize(QtCore.QSize(40, 40))
        self.BTCerar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/Cerrar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTCerar.setIcon(icon2)
        self.BTCerar.setIconSize(QtCore.QSize(28, 28))
        self.BTCerar.setObjectName("BTCerar")
        self.horizontalLayout.addWidget(self.BTCerar)
        self.verticalLayout_2.addWidget(self.FrameSuperior)
        self.FrameContenido = QtWidgets.QFrame(self.frame)
        self.FrameContenido.setStyleSheet("QFrame{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:White;\n"
"border:0px solid #14C8DC;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#A4D6DC;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#DCD8A4;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.FrameContenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameContenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameContenido.setObjectName("FrameContenido")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FrameContenido)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.FrameContenido)
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:rgba(255, 255, 255,0.3);\n"
"border: 2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:rgba(255, 255, 255,0.3);\n"
"border: 2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:White;\n"
"border:0px solid #14C8DC;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#A4D6DC;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#DCD8A4;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.BTNacional = QtWidgets.QPushButton(self.frame_2)
        self.BTNacional.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTNacional.setFont(font)
        self.BTNacional.setObjectName("BTNacional")
        self.horizontalLayout_4.addWidget(self.BTNacional)
        self.BTExtranjera = QtWidgets.QPushButton(self.frame_2)
        self.BTExtranjera.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTExtranjera.setFont(font)
        self.BTExtranjera.setObjectName("BTExtranjera")
        self.horizontalLayout_4.addWidget(self.BTExtranjera)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 5)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.TituloIzq = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.TituloIzq.setFont(font)
        self.TituloIzq.setAlignment(QtCore.Qt.AlignCenter)
        self.TituloIzq.setObjectName("TituloIzq")
        self.horizontalLayout_5.addWidget(self.TituloIzq)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 10)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.CBDivisas = QtWidgets.QComboBox(self.frame_2)
        self.CBDivisas.setMinimumSize(QtCore.QSize(0, 30))
        self.CBDivisas.setObjectName("CBDivisas")
        self.CBDivisas.addItem("")
        self.CBDivisas.setItemText(0, "")
        self.CBDivisas.addItem("")
        self.CBDivisas.addItem("")
        self.CBDivisas.addItem("")
        self.CBDivisas.addItem("")
        self.horizontalLayout_8.addWidget(self.CBDivisas)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 10)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.Cantidad = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.Cantidad.setFont(font)
        self.Cantidad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Cantidad.setObjectName("Cantidad")
        self.horizontalLayout_10.addWidget(self.Cantidad)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 10)
        self.horizontalLayout_10.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem9 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.TXCantidad = QtWidgets.QLineEdit(self.frame_2)
        self.TXCantidad.setMinimumSize(QtCore.QSize(0, 30))
        self.TXCantidad.setObjectName("TXCantidad")
        self.horizontalLayout_12.addWidget(self.TXCantidad)
        spacerItem10 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 10)
        self.horizontalLayout_12.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem11 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.Cambio = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.Cambio.setFont(font)
        self.Cambio.setObjectName("Cambio")
        self.horizontalLayout_14.addWidget(self.Cambio)
        spacerItem12 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 10)
        self.horizontalLayout_14.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem13 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.TXCambio = QtWidgets.QTextEdit(self.frame_2)
        self.TXCambio.setMinimumSize(QtCore.QSize(0, 30))
        self.TXCambio.setObjectName("TXCambio")
        self.horizontalLayout_16.addWidget(self.TXCambio)
        spacerItem14 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 10)
        self.horizontalLayout_16.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem15 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem15)
        self.BTConvertir = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTConvertir.setFont(font)
        self.BTConvertir.setObjectName("BTConvertir")
        self.horizontalLayout_19.addWidget(self.BTConvertir)
        spacerItem16 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem16)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 2)
        self.horizontalLayout_19.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 2)
        self.verticalLayout_3.setStretch(3, 2)
        self.verticalLayout_3.setStretch(4, 2)
        self.verticalLayout_3.setStretch(5, 2)
        self.verticalLayout_3.setStretch(6, 1)
        self.verticalLayout_3.setStretch(7, 2)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color:rgba(255, 255, 255,0.3);\n"
"border: 2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:White;\n"
"border:0px solid #14C8DC;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#A4D6DC;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#DCD8A4;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem17 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.BTAgregar = QtWidgets.QPushButton(self.frame_4)
        self.BTAgregar.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTAgregar.setFont(font)
        self.BTAgregar.setObjectName("BTAgregar")
        self.horizontalLayout_6.addWidget(self.BTAgregar)
        self.BTRestar = QtWidgets.QPushButton(self.frame_4)
        self.BTRestar.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTRestar.setFont(font)
        self.BTRestar.setObjectName("BTRestar")
        self.horizontalLayout_6.addWidget(self.BTRestar)
        spacerItem18 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.horizontalLayout_6.setStretch(2, 5)
        self.horizontalLayout_6.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem19 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.TituloDer = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.TituloDer.setFont(font)
        self.TituloDer.setAlignment(QtCore.Qt.AlignCenter)
        self.TituloDer.setObjectName("TituloDer")
        self.horizontalLayout_7.addWidget(self.TituloDer)
        spacerItem20 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 10)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem21 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem21)
        self.Iva = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.Iva.setFont(font)
        self.Iva.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Iva.setObjectName("Iva")
        self.horizontalLayout_9.addWidget(self.Iva)
        spacerItem22 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem22)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 10)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem23 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.TXIva = QtWidgets.QLineEdit(self.frame_4)
        self.TXIva.setMinimumSize(QtCore.QSize(0, 30))
        self.TXIva.setObjectName("TXIva")
        self.horizontalLayout_11.addWidget(self.TXIva)
        spacerItem24 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem24)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 10)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem25 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem25)
        self.Cantidad_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.Cantidad_2.setFont(font)
        self.Cantidad_2.setObjectName("Cantidad_2")
        self.horizontalLayout_13.addWidget(self.Cantidad_2)
        spacerItem26 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem26)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 10)
        self.horizontalLayout_13.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem27 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem27)
        self.TXCantidad_2 = QtWidgets.QLineEdit(self.frame_4)
        self.TXCantidad_2.setMinimumSize(QtCore.QSize(0, 30))
        self.TXCantidad_2.setObjectName("TXCantidad_2")
        self.horizontalLayout_15.addWidget(self.TXCantidad_2)
        spacerItem28 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem28)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 10)
        self.horizontalLayout_15.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem29 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem29)
        self.Resultado = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.Resultado.setFont(font)
        self.Resultado.setObjectName("Resultado")
        self.horizontalLayout_17.addWidget(self.Resultado)
        spacerItem30 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem30)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 10)
        self.horizontalLayout_17.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem31 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem31)
        self.TXResultado = QtWidgets.QTextEdit(self.frame_4)
        self.TXResultado.setMinimumSize(QtCore.QSize(0, 30))
        self.TXResultado.setObjectName("TXResultado")
        self.horizontalLayout_18.addWidget(self.TXResultado)
        spacerItem32 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem32)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 10)
        self.horizontalLayout_18.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem33 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem33)
        self.BTCalcular = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        self.BTCalcular.setFont(font)
        self.BTCalcular.setObjectName("BTCalcular")
        self.horizontalLayout_20.addWidget(self.BTCalcular)
        spacerItem34 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem34)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 2)
        self.horizontalLayout_20.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_4.setStretch(2, 2)
        self.verticalLayout_4.setStretch(3, 2)
        self.verticalLayout_4.setStretch(4, 2)
        self.verticalLayout_4.setStretch(5, 2)
        self.verticalLayout_4.setStretch(6, 2)
        self.verticalLayout_4.setStretch(7, 1)
        self.verticalLayout_4.setStretch(8, 2)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.FrameContenido)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout.addWidget(self.frame)
        Divisas.setCentralWidget(self.centralwidget)

        self.retranslateUi(Divisas)
        QtCore.QMetaObject.connectSlotsByName(Divisas)

    def retranslateUi(self, Divisas):
        _translate = QtCore.QCoreApplication.translate
        Divisas.setWindowTitle(_translate("Divisas", "MainWindow"))
        self.DESINGLASS.setText(_translate("Divisas", "Convercion de Divisas"))
        self.BTNacional.setText(_translate("Divisas", "Nacional"))
        self.BTExtranjera.setText(_translate("Divisas", "Extranjera"))
        self.TituloIzq.setText(_translate("Divisas", "Cambio de Divisas"))
        self.CBDivisas.setItemText(1, _translate("Divisas", "Dolar"))
        self.CBDivisas.setItemText(2, _translate("Divisas", "Euro"))
        self.CBDivisas.setItemText(3, _translate("Divisas", "Yuan"))
        self.CBDivisas.setItemText(4, _translate("Divisas", "Libra"))
        self.Cantidad.setText(_translate("Divisas", "Cantidad"))
        self.Cambio.setText(_translate("Divisas", "Cambio"))
        self.BTConvertir.setText(_translate("Divisas", "Convertir"))
        self.BTAgregar.setText(_translate("Divisas", "Agregar"))
        self.BTRestar.setText(_translate("Divisas", "Restar"))
        self.TituloDer.setText(_translate("Divisas", "Calculo de IVA"))
        self.Iva.setText(_translate("Divisas", "Incerte el Iva"))
        self.Cantidad_2.setText(_translate("Divisas", "Cantidad"))
        self.Resultado.setText(_translate("Divisas", "Resultado"))
        self.BTCalcular.setText(_translate("Divisas", "Calcular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Divisas = QtWidgets.QMainWindow()
    ui = Ui_Divisas()
    ui.setupUi(Divisas)
    Divisas.show()
    sys.exit(app.exec_())
