# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginInt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio(object):
    def setupUi(self, Inicio):
        Inicio.setObjectName("Inicio")
        Inicio.resize(800, 600)
        Inicio.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FrameContenido = QtWidgets.QFrame(self.frame)
        self.FrameContenido.setStyleSheet("")
        self.FrameContenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameContenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameContenido.setObjectName("FrameContenido")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FrameContenido)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FrameIzq = QtWidgets.QFrame(self.FrameContenido)
        self.FrameIzq.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 112, 192, 255), stop:1 rgba(71, 159, 164, 255));\n"
"border:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:White;\n"
"border:0px solid #14C8DC;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#A4D6DC;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#DCD8A4;\n"
"border-radius:20px;\n"
"color:Black;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"\n"
"")
        self.FrameIzq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameIzq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameIzq.setObjectName("FrameIzq")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FrameIzq)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.FrameIzq)
        self.label.setStyleSheet("border-image: url(:/cct2/Logo DesinGlass ORIGINAL.png);")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.FrameIzq)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 10)
        self.verticalLayout_5.setStretch(2, 2)
        self.verticalLayout_5.setStretch(3, 5)
        self.verticalLayout_5.setStretch(4, 1)
        self.horizontalLayout_2.addWidget(self.FrameIzq)
        self.FrameDer = QtWidgets.QFrame(self.FrameContenido)
        self.FrameDer.setStyleSheet("\n"
"")
        self.FrameDer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameDer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameDer.setObjectName("FrameDer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.FrameDer)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FrameControles = QtWidgets.QFrame(self.FrameDer)
        self.FrameControles.setStyleSheet("QFrame{\n"
"background-color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#A4D6DC;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:Brack;\n"
"border:0px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:2px solid rgb(0,0,0);\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.FrameControles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameControles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameControles.setObjectName("FrameControles")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.FrameControles)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DESINGLASS = QtWidgets.QLabel(self.FrameControles)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DESINGLASS.setFont(font)
        self.DESINGLASS.setText("")
        self.DESINGLASS.setObjectName("DESINGLASS")
        self.horizontalLayout.addWidget(self.DESINGLASS)
        spacerItem3 = QtWidgets.QSpacerItem(240, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.BTMin = QtWidgets.QPushButton(self.FrameControles)
        self.BTMin.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/Minimizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTMin.setIcon(icon)
        self.BTMin.setIconSize(QtCore.QSize(28, 28))
        self.BTMin.setObjectName("BTMin")
        self.horizontalLayout.addWidget(self.BTMin)
        self.BTMax2 = QtWidgets.QPushButton(self.FrameControles)
        self.BTMax2.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMax2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/Maximizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTMax2.setIcon(icon1)
        self.BTMax2.setIconSize(QtCore.QSize(18, 18))
        self.BTMax2.setObjectName("BTMax2")
        self.horizontalLayout.addWidget(self.BTMax2)
        self.BTMax = QtWidgets.QPushButton(self.FrameControles)
        self.BTMax.setMinimumSize(QtCore.QSize(40, 40))
        self.BTMax.setText("")
        self.BTMax.setIcon(icon1)
        self.BTMax.setIconSize(QtCore.QSize(18, 18))
        self.BTMax.setObjectName("BTMax")
        self.horizontalLayout.addWidget(self.BTMax)
        self.BTCerar = QtWidgets.QPushButton(self.FrameControles)
        self.BTCerar.setMinimumSize(QtCore.QSize(40, 40))
        self.BTCerar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/Cerrar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTCerar.setIcon(icon2)
        self.BTCerar.setIconSize(QtCore.QSize(28, 28))
        self.BTCerar.setObjectName("BTCerar")
        self.horizontalLayout.addWidget(self.BTCerar)
        self.verticalLayout_3.addWidget(self.FrameControles)
        self.FrameInfo = QtWidgets.QFrame(self.FrameDer)
        self.FrameInfo.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"}\n"
"")
        self.FrameInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameInfo.setObjectName("FrameInfo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FrameInfo)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Paginas = QtWidgets.QStackedWidget(self.FrameInfo)
        self.Paginas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Paginas.setObjectName("Paginas")
        self.Pag1 = QtWidgets.QWidget()
        self.Pag1.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:Brack;\n"
"border:0px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:2px solid rgb(0,0,0);\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#A4D6DC;\n"
"border-radius:10px;\n"
"color:Black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#DCD8A4;\n"
"border-radius:10px;\n"
"color:Black;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.Pag1.setObjectName("Pag1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Pag1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.Usuario = QtWidgets.QLabel(self.Pag1)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Usuario.setFont(font)
        self.Usuario.setObjectName("Usuario")
        self.horizontalLayout_8.addWidget(self.Usuario)
        spacerItem6 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.TXUsuario = QtWidgets.QLineEdit(self.Pag1)
        self.TXUsuario.setMinimumSize(QtCore.QSize(0, 51))
        self.TXUsuario.setStyleSheet("QLineEdit{\n"
"border-radius:20px;\n"
"}")
        self.TXUsuario.setObjectName("TXUsuario")
        self.horizontalLayout_6.addWidget(self.TXUsuario)
        spacerItem8 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 20)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem9 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.Contrasena = QtWidgets.QLabel(self.Pag1)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Contrasena.setFont(font)
        self.Contrasena.setObjectName("Contrasena")
        self.horizontalLayout_7.addWidget(self.Contrasena)
        spacerItem10 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem11 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.TXContrasena = QtWidgets.QLineEdit(self.Pag1)
        self.TXContrasena.setMinimumSize(QtCore.QSize(0, 51))
        self.TXContrasena.setStyleSheet("QLineEdit{\n"
"border-radius:20px;\n"
"}")
        self.TXContrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.TXContrasena.setObjectName("TXContrasena")
        self.horizontalLayout_5.addWidget(self.TXContrasena)
        spacerItem12 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 20)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.BTIngresar = QtWidgets.QPushButton(self.Pag1)
        self.BTIngresar.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(14)
        self.BTIngresar.setFont(font)
        self.BTIngresar.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:20px;\n"
"}\n"
"")
        self.BTIngresar.setObjectName("BTIngresar")
        self.horizontalLayout_4.addWidget(self.BTIngresar)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.BTSalir = QtWidgets.QPushButton(self.Pag1)
        self.BTSalir.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(13)
        self.BTSalir.setFont(font)
        self.BTSalir.setObjectName("BTSalir")
        self.horizontalLayout_3.addWidget(self.BTSalir)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.horizontalLayout_3.setStretch(0, 10)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem18)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 2)
        self.verticalLayout_6.setStretch(2, 2)
        self.verticalLayout_6.setStretch(3, 2)
        self.verticalLayout_6.setStretch(4, 2)
        self.verticalLayout_6.setStretch(5, 1)
        self.verticalLayout_6.setStretch(6, 2)
        self.verticalLayout_6.setStretch(7, 2)
        self.verticalLayout_6.setStretch(8, 1)
        self.Paginas.addWidget(self.Pag1)
        self.Pag2 = QtWidgets.QWidget()
        self.Pag2.setStyleSheet("")
        self.Pag2.setObjectName("Pag2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Pag2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem19 = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem19)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem20)
        self.Informacion = QtWidgets.QLabel(self.Pag2)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Informacion.setFont(font)
        self.Informacion.setAlignment(QtCore.Qt.AlignCenter)
        self.Informacion.setObjectName("Informacion")
        self.horizontalLayout_10.addWidget(self.Informacion)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem21)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        spacerItem22 = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem22)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.BarProgress = QtWidgets.QProgressBar(self.Pag2)
        self.BarProgress.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BarProgress.setFont(font)
        self.BarProgress.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.BarProgress.setStyleSheet("QProgressBar{\n"
"background-color:#ffffff;\n"
"border: 2px solid rgb(61,61,61);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"border-radius:13px;;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(71, 159, 164, 255), stop:1 rgba(0, 112, 192, 255));\n"
"border: 0px solid rgb(61,61,61);\n"
"}")
        self.BarProgress.setProperty("value", 0)
        self.BarProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.BarProgress.setTextVisible(True)
        self.BarProgress.setOrientation(QtCore.Qt.Horizontal)
        self.BarProgress.setInvertedAppearance(False)
        self.BarProgress.setObjectName("BarProgress")
        self.horizontalLayout_11.addWidget(self.BarProgress)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem24)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 4)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        spacerItem25 = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem25)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem26)
        self.Terminado = QtWidgets.QLabel(self.Pag2)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Terminado.setFont(font)
        self.Terminado.setAlignment(QtCore.Qt.AlignCenter)
        self.Terminado.setObjectName("Terminado")
        self.horizontalLayout_9.addWidget(self.Terminado)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem27)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        spacerItem28 = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem28)
        self.Paginas.addWidget(self.Pag2)
        self.Pag3 = QtWidgets.QWidget()
        self.Pag3.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:Brack;\n"
"border:0px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:2px solid rgb(0,0,0);\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#A4D6DC;\n"
"border-radius:10px;\n"
"color:Black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#DCD8A4;\n"
"border-radius:10px;\n"
"color:Black;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}\n"
"")
        self.Pag3.setObjectName("Pag3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Pag3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem29 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem29)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem30 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem30)
        self.NuevoUsuario = QtWidgets.QLabel(self.Pag3)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.NuevoUsuario.setFont(font)
        self.NuevoUsuario.setObjectName("NuevoUsuario")
        self.horizontalLayout_12.addWidget(self.NuevoUsuario)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem31)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(2, 9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem32 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem32)
        self.TXNuevoUsuario = QtWidgets.QLineEdit(self.Pag3)
        self.TXNuevoUsuario.setMinimumSize(QtCore.QSize(0, 51))
        self.TXNuevoUsuario.setStyleSheet("QLineEdit{\n"
"border-radius:20px;\n"
"}")
        self.TXNuevoUsuario.setObjectName("TXNuevoUsuario")
        self.horizontalLayout_13.addWidget(self.TXNuevoUsuario)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem33)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 20)
        self.horizontalLayout_13.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem34 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem34)
        self.Contrasena_2 = QtWidgets.QLabel(self.Pag3)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Contrasena_2.setFont(font)
        self.Contrasena_2.setObjectName("Contrasena_2")
        self.horizontalLayout_14.addWidget(self.Contrasena_2)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem35)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(2, 9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem36 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem36)
        self.TXContrasena_2 = QtWidgets.QLineEdit(self.Pag3)
        self.TXContrasena_2.setMinimumSize(QtCore.QSize(0, 51))
        self.TXContrasena_2.setStyleSheet("QLineEdit{\n"
"border-radius:20px;\n"
"}")
        self.TXContrasena_2.setObjectName("TXContrasena_2")
        self.horizontalLayout_15.addWidget(self.TXContrasena_2)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem37)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 20)
        self.horizontalLayout_15.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem38 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem38)
        self.ConfContrasena = QtWidgets.QLabel(self.Pag3)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ConfContrasena.setFont(font)
        self.ConfContrasena.setObjectName("ConfContrasena")
        self.horizontalLayout_16.addWidget(self.ConfContrasena)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem39)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.setStretch(2, 9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem40 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem40)
        self.TXCOnfContrasena = QtWidgets.QLineEdit(self.Pag3)
        self.TXCOnfContrasena.setMinimumSize(QtCore.QSize(0, 51))
        self.TXCOnfContrasena.setStyleSheet("QLineEdit{\n"
"border-radius:20px;\n"
"}")
        self.TXCOnfContrasena.setObjectName("TXCOnfContrasena")
        self.horizontalLayout_17.addWidget(self.TXCOnfContrasena)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem41)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 20)
        self.horizontalLayout_17.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem42)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem43)
        self.BTAgregar = QtWidgets.QPushButton(self.Pag3)
        self.BTAgregar.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(14)
        self.BTAgregar.setFont(font)
        self.BTAgregar.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:20px;\n"
"}\n"
"")
        self.BTAgregar.setObjectName("BTAgregar")
        self.horizontalLayout_18.addWidget(self.BTAgregar)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem44)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        spacerItem45 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem45)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 2)
        self.verticalLayout_8.setStretch(2, 2)
        self.verticalLayout_8.setStretch(3, 2)
        self.verticalLayout_8.setStretch(4, 2)
        self.verticalLayout_8.setStretch(5, 2)
        self.verticalLayout_8.setStretch(6, 2)
        self.verticalLayout_8.setStretch(7, 1)
        self.verticalLayout_8.setStretch(8, 2)
        self.verticalLayout_8.setStretch(9, 1)
        self.Paginas.addWidget(self.Pag3)
        self.Pag4 = QtWidgets.QWidget()
        self.Pag4.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:#000000ff;\n"
"color:Brack;\n"
"border:0px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:White;\n"
"border:2px solid rgb(0,0,0);\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#A4D6DC;\n"
"border-radius:10px;\n"
"color:Black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#DCD8A4;\n"
"border-radius:10px;\n"
"color:Black;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:White;\n"
"border:0px;\n"
"color:Black;\n"
"border-bottom:2px solid rgb(61,61,61);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"    gridline-color:rgb(61,61,61);\n"
"    font-size:12pt;\n"
"    color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:#A4D6DC;\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"\n"
"QTableWidgetQTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid rgb(0,206,151);\n"
"}\n"
"\n"
"QTabWidget{\n"
"background-color: rgb(129, 129, 129);\n"
"}")
        self.Pag4.setObjectName("Pag4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Pag4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem46 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem46)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem47 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem47)
        self.Usuario_2 = QtWidgets.QLabel(self.Pag4)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Usuario_2.setFont(font)
        self.Usuario_2.setObjectName("Usuario_2")
        self.horizontalLayout_19.addWidget(self.Usuario_2)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem48)
        self.BTBuscar = QtWidgets.QPushButton(self.Pag4)
        self.BTBuscar.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(14)
        self.BTBuscar.setFont(font)
        self.BTBuscar.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:20px;\n"
"}\n"
"")
        self.BTBuscar.setObjectName("BTBuscar")
        self.horizontalLayout_19.addWidget(self.BTBuscar)
        spacerItem49 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem49)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 1)
        self.horizontalLayout_19.setStretch(2, 5)
        self.horizontalLayout_19.setStretch(3, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem50 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem50)
        self.TXUsuario_2 = QtWidgets.QLineEdit(self.Pag4)
        self.TXUsuario_2.setMinimumSize(QtCore.QSize(0, 51))
        self.TXUsuario_2.setStyleSheet("QLineEdit{\n"
"border-radius:20px;\n"
"}")
        self.TXUsuario_2.setObjectName("TXUsuario_2")
        self.horizontalLayout_20.addWidget(self.TXUsuario_2)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem51)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 20)
        self.horizontalLayout_20.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem52 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem52)
        self.NuevaContrasena = QtWidgets.QLabel(self.Pag4)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.NuevaContrasena.setFont(font)
        self.NuevaContrasena.setObjectName("NuevaContrasena")
        self.horizontalLayout_21.addWidget(self.NuevaContrasena)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem53)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 1)
        self.horizontalLayout_21.setStretch(2, 9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem54 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem54)
        self.TXNuevaContrasena = QtWidgets.QLineEdit(self.Pag4)
        self.TXNuevaContrasena.setMinimumSize(QtCore.QSize(0, 51))
        self.TXNuevaContrasena.setStyleSheet("QLineEdit{\n"
"border-radius:20px;\n"
"}")
        self.TXNuevaContrasena.setObjectName("TXNuevaContrasena")
        self.horizontalLayout_22.addWidget(self.TXNuevaContrasena)
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem55)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 20)
        self.horizontalLayout_22.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem56 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem56)
        self.ConfirmarContrasena = QtWidgets.QLabel(self.Pag4)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmarContrasena.setFont(font)
        self.ConfirmarContrasena.setObjectName("ConfirmarContrasena")
        self.horizontalLayout_23.addWidget(self.ConfirmarContrasena)
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem57)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 1)
        self.horizontalLayout_23.setStretch(2, 9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem58 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem58)
        self.TXConfirmarContrasena = QtWidgets.QLineEdit(self.Pag4)
        self.TXConfirmarContrasena.setMinimumSize(QtCore.QSize(0, 51))
        self.TXConfirmarContrasena.setStyleSheet("QLineEdit{\n"
"border-radius:20px;\n"
"}")
        self.TXConfirmarContrasena.setObjectName("TXConfirmarContrasena")
        self.horizontalLayout_24.addWidget(self.TXConfirmarContrasena)
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem59)
        self.horizontalLayout_24.setStretch(0, 1)
        self.horizontalLayout_24.setStretch(1, 20)
        self.horizontalLayout_24.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        spacerItem60 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem60)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem61)
        self.BTActualizar = QtWidgets.QPushButton(self.Pag4)
        self.BTActualizar.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(14)
        self.BTActualizar.setFont(font)
        self.BTActualizar.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:20px;\n"
"}\n"
"")
        self.BTActualizar.setObjectName("BTActualizar")
        self.horizontalLayout_25.addWidget(self.BTActualizar)
        spacerItem62 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem62)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 1)
        self.horizontalLayout_25.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        spacerItem63 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem63)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 2)
        self.verticalLayout_9.setStretch(2, 2)
        self.verticalLayout_9.setStretch(3, 2)
        self.verticalLayout_9.setStretch(4, 2)
        self.verticalLayout_9.setStretch(5, 2)
        self.verticalLayout_9.setStretch(6, 2)
        self.verticalLayout_9.setStretch(7, 1)
        self.verticalLayout_9.setStretch(8, 2)
        self.verticalLayout_9.setStretch(9, 1)
        self.Paginas.addWidget(self.Pag4)
        self.verticalLayout_4.addWidget(self.Paginas)
        self.verticalLayout_3.addWidget(self.FrameInfo)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 10)
        self.horizontalLayout_2.addWidget(self.FrameDer)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.addWidget(self.FrameContenido)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout.addWidget(self.frame)
        Inicio.setCentralWidget(self.centralwidget)

        self.retranslateUi(Inicio)
        self.Paginas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Inicio)

    def retranslateUi(self, Inicio):
        _translate = QtCore.QCoreApplication.translate
        Inicio.setWindowTitle(_translate("Inicio", "MainWindow"))
        self.label_2.setText(_translate("Inicio", "INICIO DE SESION"))
        self.Usuario.setText(_translate("Inicio", "Usuario"))
        self.Contrasena.setText(_translate("Inicio", "Contraseña"))
        self.BTIngresar.setText(_translate("Inicio", "Ingresar"))
        self.BTSalir.setText(_translate("Inicio", "Salir"))
        self.Informacion.setText(_translate("Inicio", "Cargando Recursos . . ."))
        self.Terminado.setText(_translate("Inicio", "Terminado"))
        self.NuevoUsuario.setText(_translate("Inicio", "Usuario"))
        self.Contrasena_2.setText(_translate("Inicio", "Contraseña"))
        self.ConfContrasena.setText(_translate("Inicio", "Confirmar Contraseña"))
        self.BTAgregar.setText(_translate("Inicio", "Agregar"))
        self.Usuario_2.setText(_translate("Inicio", "Usuario"))
        self.BTBuscar.setText(_translate("Inicio", "Buscar"))
        self.NuevaContrasena.setText(_translate("Inicio", "Contraseña"))
        self.ConfirmarContrasena.setText(_translate("Inicio", "Confirmar Contraseña"))
        self.BTActualizar.setText(_translate("Inicio", "Actualizar"))
import logo2_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inicio = QtWidgets.QMainWindow()
    ui = Ui_Inicio()
    ui.setupUi(Inicio)
    Inicio.show()
    sys.exit(app.exec_())
